"""HTML renderer (SDLC-064, rewritten for v0.9.0 — SDLC-069).

The v0.8.0 renderer mirrored the Markdown structure section-for-section.
That was a shortcut. The v0.9.0 renderer is structured as a diligence-grade
report:

1. **Header band** with archetype, profile, and analysis timestamp.
2. **Executive callout** — the bottom-line for the chosen persona, leading
   with three persona-specific facts (e.g. "Bus factor of 1, no lockfile,
   12 critical blockers" for an acquisition-diligence audience).
3. **Scorecard** — single-screen card grid with score, verdict, blocker
   counts, and finding counts (production vs fixture-derived, segregated).
4. **Persona narrative sections** — one section per
   ``narrative_emphasis`` term in the use-case profile. Generated by the
   ``narrative_blocks`` builders (SDLC-068), so the same data drives both
   the Markdown and HTML outputs.
5. **Hard blockers** — pre-action callout box listing each one with
   closure requirements.
6. **Top risks** — top-5 production findings (fixture findings in §10.2).
7. **Quantitative inventory** — definition list.
8. **Category scoring matrix** — sortable table.
9. **Detailed findings** — split into 9.1 (production, sortable) and
   9.2 (fixture / non-production, collapsed by default).
10. **Evidence appendix** — finding count.

The page uses an embedded stylesheet, an embedded sort-script, and works
offline. Print stylesheet collapses sortable headers and reflows for A4.
"""

from __future__ import annotations

import html
import warnings
from collections import defaultdict
from datetime import UTC, datetime

from sdlc_assessor.normalizer.findings import is_fixture_finding
from sdlc_assessor.profiles.loader import load_use_case_profiles
from sdlc_assessor.renderer.persona import (
    NarrativeBlock,
    narrate_for_persona,
)

_SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
_SEVERITY_RANK = {"critical": 5, "high": 4, "medium": 3, "low": 2, "info": 1}
_CONFIDENCE_RANK = {"high": 1.0, "medium": 0.9, "low": 0.7}

_INVENTORY_FIELDS = (
    ("source_files", "Source files"),
    ("source_loc", "Source LOC"),
    ("test_files", "Test files"),
    ("estimated_test_cases", "Estimated test cases"),
    ("test_to_source_ratio", "Test-to-source ratio"),
    ("workflow_files", "Workflow files"),
    ("workflow_jobs", "Workflow jobs"),
    ("runtime_dependencies", "Runtime dependencies"),
    ("dev_dependencies", "Dev dependencies"),
    ("commit_count", "Commit count"),
    ("tag_count", "Tag count"),
    ("release_count", "Release count"),
)


_STYLESHEET = """
:root {
  --bg: #ffffff;
  --bg-alt: #f7f8fa;
  --fg: #111317;
  --muted: #5d6470;
  --accent: #0058a3;
  --accent-fg: #ffffff;
  --border: #d8dade;
  --row-alt: #f7f8fa;
  --critical-bg: #fbe9e9;
  --critical-fg: #861818;
  --high-bg: #fff0e0;
  --high-fg: #803e00;
  --medium-bg: #fff8d6;
  --medium-fg: #6a5500;
  --low-bg: #eef5ff;
  --low-fg: #1d4380;
  --info-bg: #f0f0f0;
  --info-fg: #555a60;
  --pass-bg: #e7f5ec;
  --pass-fg: #155b2a;
  --fail-bg: #fbe9e9;
  --fail-fg: #861818;
  --conditional-bg: #fff5e1;
  --conditional-fg: #7a4f00;
}

* { box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
  font-size: 15px;
  color: var(--fg);
  background: var(--bg);
  margin: 0;
  line-height: 1.55;
}
.container {
  max-width: 1180px;
  margin: 0 auto;
  padding: 2.4rem 2rem 4rem;
}

/* Header band */
.report-header {
  border-bottom: 1px solid var(--border);
  padding-bottom: 1.6rem;
  margin-bottom: 2.2rem;
}
.report-header h1 {
  font-size: 1.85rem;
  margin: 0 0 0.4rem;
  letter-spacing: -0.01em;
}
.report-header .meta {
  display: flex;
  flex-wrap: wrap;
  gap: 0.4rem 1.4rem;
  color: var(--muted);
  font-size: 0.93rem;
}
.report-header .meta strong { color: var(--fg); font-weight: 600; }

/* Executive callout */
.exec-callout {
  background: var(--bg-alt);
  border-left: 6px solid var(--accent);
  padding: 1.4rem 1.6rem;
  margin-bottom: 2.2rem;
  border-radius: 4px;
}
.exec-callout h2 {
  font-size: 0.78rem;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  margin: 0 0 0.6rem;
  color: var(--muted);
}
.exec-callout .headline {
  font-size: 1.15rem;
  font-weight: 600;
  margin-bottom: 0.7rem;
  line-height: 1.45;
}
.exec-callout .lede {
  margin: 0 0 0.7rem;
  color: var(--fg);
}
.exec-callout ul {
  margin: 0.6rem 0 0;
  padding-left: 1.3rem;
}
.exec-callout li { margin-bottom: 0.3rem; }

/* Scorecard */
.scorecard {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
  gap: 0.9rem;
  margin: 0 0 2.2rem;
}
.score-card {
  background: var(--bg-alt);
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 0.95rem 1.1rem;
}
.score-card .label {
  font-size: 0.74rem;
  text-transform: uppercase;
  letter-spacing: 0.07em;
  color: var(--muted);
  margin-bottom: 0.35rem;
}
.score-card .value {
  font-size: 1.55rem;
  font-weight: 700;
  letter-spacing: -0.01em;
}
.score-card .sublabel {
  margin-top: 0.25rem;
  color: var(--muted);
  font-size: 0.86rem;
}

/* Verdict pill */
.verdict-pill {
  display: inline-block;
  padding: 0.18rem 0.7rem;
  border-radius: 999px;
  font-size: 0.92rem;
  font-weight: 600;
}
.verdict-pass_with_distinction { background: var(--pass-bg); color: var(--pass-fg); }
.verdict-pass { background: var(--pass-bg); color: var(--pass-fg); }
.verdict-conditional_pass { background: var(--conditional-bg); color: var(--conditional-fg); }
.verdict-fail { background: var(--fail-bg); color: var(--fail-fg); }

/* Section headers */
section.report-section { margin: 2.4rem 0; }
section.report-section h2 {
  font-size: 1.35rem;
  margin: 0 0 0.7rem;
  letter-spacing: -0.005em;
  border-bottom: 1px solid var(--border);
  padding-bottom: 0.4rem;
}
section.report-section h3 {
  font-size: 1.05rem;
  margin: 1.4rem 0 0.5rem;
  font-weight: 600;
}

/* Narrative blocks */
.narrative-block {
  background: var(--bg);
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 1.1rem 1.3rem;
  margin: 1rem 0;
}
.narrative-block .summary {
  margin: 0 0 0.9rem;
  color: var(--fg);
}
.narrative-block .facts {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
  gap: 0.4rem 1.2rem;
  margin: 0.5rem 0 0.9rem;
}
.narrative-block .fact {
  display: flex;
  justify-content: space-between;
  gap: 0.6rem;
  padding: 0.25rem 0;
  border-bottom: 1px dotted var(--border);
}
.narrative-block .fact .label { color: var(--muted); font-size: 0.92rem; }
.narrative-block .fact .value { font-weight: 600; font-size: 0.92rem; text-align: right; }
.narrative-block .fact.sev-critical .value { color: var(--critical-fg); }
.narrative-block .fact.sev-high .value { color: var(--high-fg); }
.narrative-block .fact.sev-medium .value { color: var(--medium-fg); }
.narrative-block .callouts { margin-top: 0.7rem; }
.narrative-block .callout {
  padding: 0.55rem 0.85rem;
  border-radius: 4px;
  margin: 0.4rem 0;
  font-size: 0.94rem;
}
.callout-critical { background: var(--critical-bg); color: var(--critical-fg); border-left: 3px solid var(--critical-fg); }
.callout-high { background: var(--high-bg); color: var(--high-fg); border-left: 3px solid var(--high-fg); }
.callout-medium { background: var(--medium-bg); color: var(--medium-fg); border-left: 3px solid var(--medium-fg); }
.callout-low { background: var(--low-bg); color: var(--low-fg); border-left: 3px solid var(--low-fg); }
.callout-info { background: var(--info-bg); color: var(--info-fg); border-left: 3px solid var(--info-fg); }

/* Tables */
table.data {
  border-collapse: collapse;
  width: 100%;
  font-size: 0.93rem;
  margin: 0.5rem 0 1.4rem;
}
table.data th, table.data td {
  padding: 0.5rem 0.7rem;
  text-align: left;
  border-bottom: 1px solid var(--border);
  vertical-align: top;
}
table.data thead th {
  background: var(--bg-alt);
  cursor: pointer;
  user-select: none;
  font-size: 0.86rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  color: var(--muted);
}
table.data thead th[aria-sort="ascending"]::after { content: " ▲"; color: var(--accent); }
table.data thead th[aria-sort="descending"]::after { content: " ▼"; color: var(--accent); }
table.data tr:hover td { background: var(--bg-alt); }

/* Severity cells */
.sev-critical .sev-cell { background: var(--critical-bg); color: var(--critical-fg); font-weight: 700; padding: 0.2rem 0.55rem; border-radius: 3px; }
.sev-high .sev-cell { background: var(--high-bg); color: var(--high-fg); font-weight: 700; padding: 0.2rem 0.55rem; border-radius: 3px; }
.sev-medium .sev-cell { background: var(--medium-bg); color: var(--medium-fg); font-weight: 600; padding: 0.2rem 0.55rem; border-radius: 3px; }
.sev-low .sev-cell { background: var(--low-bg); color: var(--low-fg); padding: 0.2rem 0.55rem; border-radius: 3px; }
.sev-info .sev-cell { background: var(--info-bg); color: var(--info-fg); padding: 0.2rem 0.55rem; border-radius: 3px; }

code, .mono { font-family: SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace; font-size: 0.9em; }
code { background: var(--row-alt); padding: 0.1em 0.35em; border-radius: 3px; }

/* Definition list (inventory + classification) */
dl.kv {
  display: grid;
  grid-template-columns: 220px 1fr;
  gap: 0.4rem 1.2rem;
  margin: 0.5rem 0 1.4rem;
}
dl.kv dt { color: var(--muted); font-size: 0.92rem; }
dl.kv dd { margin: 0; font-weight: 500; }

/* Hard-blocker pre-action */
.hard-blockers {
  background: var(--critical-bg);
  border: 1px solid var(--critical-fg);
  border-radius: 6px;
  padding: 1.1rem 1.3rem;
  margin: 1rem 0;
}
.hard-blockers h3 {
  color: var(--critical-fg);
  margin: 0 0 0.6rem;
  font-size: 1.05rem;
}
.hard-blockers .blocker {
  background: white;
  border-radius: 4px;
  padding: 0.6rem 0.85rem;
  margin: 0.45rem 0;
}

/* Findings groupings */
details.fixture-section {
  background: var(--bg-alt);
  border: 1px dashed var(--border);
  padding: 0.8rem 1rem;
  border-radius: 6px;
  margin: 1rem 0;
}
details.fixture-section summary {
  cursor: pointer;
  color: var(--muted);
  font-size: 0.94rem;
  font-weight: 600;
}
details.fixture-section summary:hover { color: var(--fg); }

/* Print */
@media print {
  body { font-size: 11.5pt; color: #000; }
  .container { max-width: 100%; padding: 0.5cm 1cm; }
  table.data thead th { cursor: default; }
  details.fixture-section[open] { page-break-before: always; }
  .scorecard { page-break-inside: avoid; }
  .narrative-block { page-break-inside: avoid; }
}
"""


_SORT_SCRIPT = """
document.querySelectorAll('table.sortable').forEach(function(t) {
  t.querySelectorAll('thead th').forEach(function(th, idx) {
    th.addEventListener('click', function() {
      var rows = Array.from(t.querySelectorAll('tbody tr'));
      var current = th.getAttribute('aria-sort');
      var next = current === 'ascending' ? 'descending' : 'ascending';
      t.querySelectorAll('thead th').forEach(function(o) { o.removeAttribute('aria-sort'); });
      th.setAttribute('aria-sort', next);
      rows.sort(function(a, b) {
        var av = a.children[idx].getAttribute('data-sort') || a.children[idx].textContent.trim();
        var bv = b.children[idx].getAttribute('data-sort') || b.children[idx].textContent.trim();
        var an = parseFloat(av); var bn = parseFloat(bv);
        if (!Number.isNaN(an) && !Number.isNaN(bn)) {
          return next === 'ascending' ? an - bn : bn - an;
        }
        return next === 'ascending' ? av.localeCompare(bv) : bv.localeCompare(av);
      });
      var tbody = t.querySelector('tbody');
      rows.forEach(function(r) { tbody.appendChild(r); });
    });
  });
});
"""


def _esc(value: object) -> str:
    return html.escape(str(value), quote=True) if value is not None else ""


def _normalize_category_scores(raw: object) -> list[dict]:
    if isinstance(raw, list):
        return [r for r in raw if isinstance(r, dict)]
    if isinstance(raw, dict):
        warnings.warn(
            "scoring.category_scores is in the legacy dict shape; converting "
            "for HTML rendering.",
            DeprecationWarning,
            stacklevel=2,
        )
        out: list[dict] = []
        for cat, data in raw.items():
            applicability = data.get("applicability", "applicable")
            out.append(
                {
                    "category": cat,
                    "applicable": applicability != "not_applicable",
                    "score": int(round(data.get("score", 0))),
                    "max_score": int(round(data.get("max", data.get("max_score", 0)))),
                    "summary": data.get("summary", ""),
                    "key_findings": data.get("key_findings", []),
                }
            )
        return out
    return []


def _finding_rank(f: dict) -> float:
    sev = _SEVERITY_RANK.get(f.get("severity", "low"), 0)
    conf = _CONFIDENCE_RANK.get(f.get("confidence", "medium"), 0.0)
    mag = float(f.get("score_impact", {}).get("magnitude", 0)) / 10.0
    return sev * conf * mag


def _split_findings(findings: list[dict]) -> tuple[list[dict], list[dict]]:
    production: list[dict] = []
    fixture: list[dict] = []
    for f in findings:
        if is_fixture_finding(f):
            fixture.append(f)
        else:
            production.append(f)
    return production, fixture


def _resolve_use_case_profile(use_case: str | None) -> dict | None:
    if not use_case:
        return None
    try:
        all_profiles = load_use_case_profiles()
    except Exception:
        return None
    return all_profiles.get(use_case) or None


def _exec_callout_html(scored: dict, blocks: list[NarrativeBlock]) -> str:
    scoring = scored.get("scoring") or {}
    classification = scored.get("classification") or {}
    overall = scoring.get("overall_score", "n/a")
    verdict = scoring.get("verdict", "n/a")
    archetype = classification.get("repo_archetype", "unknown")
    crit = sum(1 for b in scored.get("hard_blockers") or [] if b.get("severity") == "critical")
    high = sum(1 for b in scored.get("hard_blockers") or [] if b.get("severity") == "high")

    headline_parts: list[str] = []
    headline_parts.append(
        f"Overall <strong>{_esc(overall)}/100</strong>"
        f" — verdict <span class=\"verdict-pill verdict-{_esc(verdict)}\">{_esc(verdict)}</span>"
    )
    if crit or high:
        sev_summary: list[str] = []
        if crit:
            sev_summary.append(f"<strong>{crit}</strong> critical")
        if high:
            sev_summary.append(f"<strong>{high}</strong> high")
        headline_parts.append(f"with {' and '.join(sev_summary)} blocker{'s' if (crit + high) != 1 else ''}")
    else:
        headline_parts.append("with no hard blockers")
    headline_parts.append(f"on a {_esc(archetype)} archetype")
    headline = ", ".join(headline_parts) + "."

    # Pull the first 1–2 narrative summaries to form the lede prose.
    lede_html = ""
    if blocks:
        first = blocks[0]
        lede_html = f'<p class="lede">{_esc(first.summary)}</p>'

    # Pull a short bulleted list of the strongest callouts across all blocks.
    callouts: list[tuple[str, str]] = []
    for b in blocks:
        for c in b.callouts:
            callouts.append((c.severity, c.message))
    # De-dupe and pick top 4 by severity rank.
    seen: set[str] = set()
    sorted_callouts: list[tuple[str, str]] = []
    for sev, msg in sorted(
        callouts, key=lambda t: -_SEVERITY_RANK.get(t[0], 0)
    ):
        if msg in seen:
            continue
        seen.add(msg)
        sorted_callouts.append((sev, msg))
        if len(sorted_callouts) >= 4:
            break
    bullets_html = ""
    if sorted_callouts:
        items = "".join(
            f'<li><span class="verdict-pill verdict-{_esc(sev)}">{_esc(sev)}</span> {_esc(msg)}</li>'
            for sev, msg in sorted_callouts
        )
        bullets_html = f"<ul>{items}</ul>"

    return (
        '<aside class="exec-callout" aria-label="Executive summary">'
        '<h2>Executive summary</h2>'
        f'<p class="headline">{headline}</p>'
        f"{lede_html}"
        f"{bullets_html}"
        "</aside>"
    )


def _scorecard_html(scored: dict, *, prod_findings: int, fixture_count: int) -> str:
    scoring = scored.get("scoring") or {}
    overall = scoring.get("overall_score", "n/a")
    verdict = scoring.get("verdict", "n/a")
    confidence = scoring.get("score_confidence", "n/a")
    blockers = scored.get("hard_blockers") or []
    crit = sum(1 for b in blockers if b.get("severity") == "critical")
    high = sum(1 for b in blockers if b.get("severity") == "high")
    classification = scored.get("classification") or {}

    cards = [
        ("Overall", str(_esc(overall)), "of 100"),
        (
            "Verdict",
            f'<span class="verdict-pill verdict-{_esc(verdict)}">{_esc(verdict)}</span>',
            f"score confidence: {_esc(confidence)}",
        ),
        (
            "Hard blockers",
            f"{crit + high}",
            f"{crit} critical · {high} high",
        ),
        (
            "Production findings",
            str(prod_findings),
            f"+ {fixture_count} fixture-derived (segregated)",
        ),
        (
            "Archetype",
            _esc(classification.get("repo_archetype", "unknown")),
            f"maturity: {_esc(classification.get('maturity_profile', 'unknown'))}",
        ),
        (
            "Classification confidence",
            f"{float(classification.get('classification_confidence') or 0.0):.2f}",
            "of 1.0",
        ),
    ]
    cards_html = "".join(
        f'<div class="score-card">'
        f'<div class="label">{label}</div>'
        f'<div class="value">{value}</div>'
        f'<div class="sublabel">{sublabel}</div>'
        f"</div>"
        for label, value, sublabel in cards
    )
    return f'<div class="scorecard">{cards_html}</div>'


def _narrative_block_html(block: NarrativeBlock) -> str:
    facts_html = ""
    if block.facts:
        rows = "".join(
            f'<div class="fact{(" sev-" + _esc(fact.severity)) if fact.severity else ""}">'
            f'<span class="label">{_esc(fact.label)}</span>'
            f'<span class="value">{_esc(fact.value)}</span>'
            f"</div>"
            for fact in block.facts
        )
        facts_html = f'<div class="facts">{rows}</div>'

    callouts_html = ""
    if block.callouts:
        lines = "".join(
            f'<div class="callout callout-{_esc(c.severity)}">{_esc(c.message)}</div>'
            for c in block.callouts
        )
        callouts_html = f'<div class="callouts">{lines}</div>'

    return (
        '<article class="narrative-block">'
        f"<h3>{_esc(block.title)}</h3>"
        f'<p class="summary">{_esc(block.summary)}</p>'
        f"{facts_html}"
        f"{callouts_html}"
        "</article>"
    )


def _hard_blockers_html(scored: dict) -> str:
    blockers = scored.get("hard_blockers") or []
    if not blockers:
        return (
            '<section class="report-section">'
            "<h2>Hard blockers</h2>"
            '<p class="muted">No hard blockers were triggered.</p>'
            "</section>"
        )
    items: list[str] = []
    for b in blockers:
        sev = (b.get("severity") or "?").lower()
        title = _esc(b.get("title", "(no title)"))
        reason = _esc(b.get("reason", ""))
        closures = b.get("closure_requirements") or []
        cl_html = (
            "<ul>" + "".join(f"<li>{_esc(c)}</li>" for c in closures) + "</ul>"
            if closures
            else ""
        )
        items.append(
            f'<div class="blocker"><strong>{_esc(sev.upper())}</strong> {title}'
            f' — {reason}{cl_html}</div>'
        )
    return (
        '<section class="report-section">'
        "<h2>Hard blockers</h2>"
        '<div class="hard-blockers">'
        f'<h3>{len(blockers)} blocker(s) — close before merge</h3>'
        + "".join(items)
        + "</div></section>"
    )


def _findings_table_html(findings: list[dict], *, table_id: str = "") -> str:
    if not findings:
        return '<p class="muted">No findings to display.</p>'
    rows: list[str] = []
    for f in findings:
        sev = (f.get("severity") or "info").lower()
        ev = (f.get("evidence") or [{}])[0]
        path = _esc(ev.get("path", "n/a"))
        line = ev.get("line_start")
        path_ref = f"{path}:{line}" if line else path
        rows.append(
            f'<tr class="sev-{_esc(sev)}">'
            f'<td data-sort="{_SEVERITY_RANK.get(sev, 0)}"><span class="sev-cell">{_esc(sev.upper())}</span></td>'
            f'<td>{_esc(f.get("category", "?"))}</td>'
            f'<td><code>{_esc(f.get("subcategory", "?"))}</code></td>'
            f'<td>{_esc(f.get("statement", ""))}</td>'
            f'<td><code>{_esc(path_ref)}</code></td>'
            f"</tr>"
        )
    return (
        f'<table class="data sortable" id="{_esc(table_id)}">\n'
        '  <thead><tr>'
        '<th>Severity</th><th>Category</th><th>Subcategory</th>'
        '<th>Statement</th><th>Location</th>'
        "</tr></thead>\n"
        f"  <tbody>{''.join(rows)}</tbody>\n"
        "</table>"
    )


def _category_scoring_table_html(category_scores: list[dict]) -> str:
    rows: list[str] = []
    for cat in category_scores:
        applicable = "yes" if cat.get("applicable") else "no"
        if not cat.get("applicable"):
            score_cell, max_cell = "—", "—"
        else:
            score_cell = _esc(cat.get("score", 0))
            max_cell = _esc(cat.get("max_score", 0))
        rows.append(
            "<tr>"
            f'<td>{_esc(cat.get("category", "?"))}</td>'
            f'<td>{applicable}</td>'
            f'<td data-sort="{cat.get("score", 0) if cat.get("applicable") else -1}">{score_cell}</td>'
            f'<td>{max_cell}</td>'
            f'<td>{_esc(cat.get("summary", ""))}</td>'
            "</tr>"
        )
    return (
        '<table class="data sortable">\n'
        '  <thead><tr><th>Category</th><th>Applicable</th><th>Score</th><th>Max</th><th>Summary</th></tr></thead>\n'
        f"  <tbody>{''.join(rows)}</tbody>\n"
        "</table>"
    )


def _findings_grouped_by_category_html(findings: list[dict]) -> str:
    if not findings:
        return '<p class="muted">No production findings to display.</p>'
    bucket: dict[str, list[dict]] = defaultdict(list)
    for f in findings:
        bucket[f.get("category", "unknown")].append(f)
    blocks: list[str] = []
    for cat in sorted(bucket.keys()):
        sorted_in_cat = sorted(bucket[cat], key=lambda f: _SEVERITY_ORDER.get(f.get("severity", "low"), 5))
        items: list[str] = []
        for f in sorted_in_cat:
            sev = (f.get("severity") or "info").lower()
            ev = (f.get("evidence") or [{}])[0]
            path = ev.get("path", "")
            line = ev.get("line_start")
            path_ref = f"{path}:{line}" if line else path
            items.append(
                f'<li class="sev-{_esc(sev)}">'
                f'<span class="sev-cell">{_esc(sev.upper())}</span> '
                f"{_esc(f.get('statement', ''))} — <code>{_esc(path_ref)}</code>"
                f"</li>"
            )
        blocks.append(f"<h3>{_esc(cat)}</h3><ul>{''.join(items)}</ul>")
    return "\n".join(blocks)


def render_html_report(scored: dict) -> str:
    repo_meta = scored.get("repo_meta", {}) or {}
    classification = scored.get("classification", {}) or {}
    scoring = scored.get("scoring", {}) or {}
    findings = scored.get("findings") or []
    inventory = scored.get("inventory", {}) or {}
    category_scores = _normalize_category_scores(scoring.get("category_scores", []))

    prod_findings, fixture_findings_list = _split_findings(findings)

    eff = scoring.get("effective_profile", {}) or {}
    use_case = eff.get("use_case")
    use_case_profile = _resolve_use_case_profile(use_case) or {}
    blocks = narrate_for_persona(scored, use_case_profile)

    page_title = f"SDLC Assessment — {_esc(repo_meta.get('name', 'unknown'))}"

    parts: list[str] = []
    parts.append("<!DOCTYPE html>")
    parts.append('<html lang="en">')
    parts.append("<head>")
    parts.append('<meta charset="utf-8">')
    parts.append(f"<title>{page_title}</title>")
    parts.append('<meta name="viewport" content="width=device-width, initial-scale=1">')
    parts.append(f"<style>{_STYLESHEET}</style>")
    parts.append("</head>")
    parts.append("<body>")
    parts.append('<div class="container">')

    # Header band
    parts.append('<header class="report-header">')
    parts.append(f"<h1>{page_title}</h1>")
    parts.append('<div class="meta">')
    parts.append(f'<span><strong>Use case</strong> {_esc(use_case or "n/a")}</span>')
    parts.append(
        f'<span><strong>Maturity</strong> {_esc(eff.get("maturity", "n/a"))}</span>'
    )
    parts.append(
        f'<span><strong>Repo type</strong> {_esc(eff.get("repo_type", "n/a"))}</span>'
    )
    parts.append(
        f'<span><strong>Branch</strong> <code>{_esc(repo_meta.get("default_branch", "unknown"))}</code></span>'
    )
    parts.append(
        f'<span><strong>Analyzed</strong> {_esc(repo_meta.get("analysis_timestamp", datetime.now(UTC).isoformat()))}</span>'
    )
    parts.append("</div>")
    parts.append("</header>")

    # Executive callout
    parts.append(_exec_callout_html(scored, blocks))

    # Scorecard
    parts.append(
        _scorecard_html(
            scored,
            prod_findings=len(prod_findings),
            fixture_count=len(fixture_findings_list),
        )
    )

    # Persona narrative sections
    if blocks:
        parts.append('<section class="report-section">')
        parts.append(
            f'<h2>Persona-aware narrative — <code>{_esc(use_case or "n/a")}</code></h2>'
        )
        parts.append(
            '<p class="muted">Generated from the use-case profile\'s narrative_emphasis terms.</p>'
        )
        for b in blocks:
            parts.append(_narrative_block_html(b))
        parts.append("</section>")

    # Hard blockers
    parts.append(_hard_blockers_html(scored))

    # Quantitative inventory
    parts.append('<section class="report-section">')
    parts.append("<h2>Quantitative inventory</h2>")
    parts.append('<dl class="kv">')
    for key, label in _INVENTORY_FIELDS:
        value = inventory.get(key)
        parts.append(
            f"<dt>{_esc(label)}</dt><dd>{_esc(value if value is not None else 'n/a')}</dd>"
        )
    # Surface a couple of classification fields useful in the inventory view.
    parts.append(
        f"<dt>Network exposure</dt><dd>{_esc(classification.get('network_exposure', 'n/a'))}</dd>"
    )
    parts.append(
        f"<dt>Release surface</dt><dd>{_esc(classification.get('release_surface', 'n/a'))}</dd>"
    )
    parts.append("</dl>")
    parts.append("</section>")

    # Category scoring matrix
    parts.append('<section class="report-section">')
    parts.append("<h2>Category scoring matrix</h2>")
    parts.append(_category_scoring_table_html(category_scores))
    parts.append("</section>")

    # Detailed findings — production-first, fixtures collapsed
    parts.append('<section class="report-section">')
    parts.append("<h2>Detailed findings</h2>")
    parts.append("<h3>Production findings (sortable)</h3>")
    ranked_prod = sorted(prod_findings, key=lambda f: -_finding_rank(f))
    parts.append(_findings_table_html(ranked_prod, table_id="prod-findings"))
    parts.append("<h3>Production findings by category</h3>")
    parts.append(_findings_grouped_by_category_html(prod_findings))
    if fixture_findings_list:
        parts.append(
            f'<details class="fixture-section">'
            f"<summary>Fixture / non-production findings "
            f"({len(fixture_findings_list)}) — click to expand</summary>"
            '<p class="muted">These findings come from <code>tests/fixtures/</code>, '
            "<code>examples/</code>, <code>vendor/</code> or similar non-production paths. "
            "They are real signals (the tool is detecting its own intentional fixtures) "
            "but should not be confused with findings in production source.</p>"
        )
        ranked_fix = sorted(fixture_findings_list, key=lambda f: -_finding_rank(f))
        parts.append(_findings_table_html(ranked_fix, table_id="fixture-findings"))
        parts.append("</details>")
    parts.append("</section>")

    # Evidence appendix
    parts.append('<section class="report-section">')
    parts.append("<h2>Evidence appendix</h2>")
    parts.append(
        f"<p>Total findings: <strong>{len(findings)}</strong> "
        f"({len(prod_findings)} production · {len(fixture_findings_list)} fixture-derived).</p>"
    )
    parts.append(
        f"<p>Hard blockers: <strong>{len(scored.get('hard_blockers') or [])}</strong>. "
        f"Detector packs registered: see <code>scoring.applied_weights</code> in the JSON artifact.</p>"
    )
    parts.append("</section>")

    parts.append("</div>")  # /.container
    parts.append(f"<script>{_SORT_SCRIPT}</script>")
    parts.append("</body></html>")
    return "\n".join(parts) + "\n"


__all__ = ["render_html_report"]
