"""Markdown renderer (rewritten v0.9.0 — SDLC-070).

Same data layout as the v0.9.0 HTML renderer (SDLC-069):

1. **Header** — repo name, profile triple, branch, analysis time.
2. **Executive summary** — bottom-line for the chosen persona, leading
   with the strongest persona-relevant facts.
3. **Scorecard** — overall score, verdict, blocker counts, finding
   counts (production vs fixture-derived).
4. **Persona narrative sections** — one block per
   ``narrative_emphasis`` term in the use-case profile, generated by
   the shared ``narrative_blocks`` builders.
5. **Hard blockers** — pre-action callout listing each blocker plus
   closure requirements.
6. **Quantitative inventory** — definition list.
7. **Category scoring matrix** — one row per category.
8. **Detailed findings** — production-first table; fixture-derived
   findings collapsed into a labelled subsection.
9. **Evidence appendix** — finding count + per-finding index.

The Markdown surface preserves backward-compatibility with v0.8.0 readers:
all prior section headings either survive (renamed when they add value)
or fold into the new persona narrative.
"""

from __future__ import annotations

import warnings
from collections import defaultdict
from datetime import UTC, datetime

from sdlc_assessor.normalizer.findings import is_fixture_finding
from sdlc_assessor.profiles.loader import load_use_case_profiles
from sdlc_assessor.renderer.persona import NarrativeBlock, narrate_for_persona

SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
SEVERITY_RANK = {"critical": 5, "high": 4, "medium": 3, "low": 2, "info": 1}
CONFIDENCE_RANK = {"high": 1.0, "medium": 0.9, "low": 0.7}

INVENTORY_FIELDS = [
    ("source_files", "Source files"),
    ("source_loc", "Source LOC"),
    ("test_files", "Test files"),
    ("estimated_test_cases", "Estimated test cases"),
    ("test_to_source_ratio", "Test-to-source ratio"),
    ("workflow_files", "Workflow files"),
    ("workflow_jobs", "Workflow jobs"),
    ("runtime_dependencies", "Runtime dependencies"),
    ("dev_dependencies", "Dev dependencies"),
    ("commit_count", "Commit count"),
    ("tag_count", "Tag count"),
    ("release_count", "Release count"),
]


def _normalize_category_scores(raw):
    """Convert legacy dict-of-cats to list-of-cats (back-compat for SDLC-015)."""
    if isinstance(raw, list):
        return raw
    if isinstance(raw, dict):
        warnings.warn(
            "scoring.category_scores is in the legacy dict shape; "
            "convert to list-of-dicts per docs/evidence_schema.json. "
            "This back-compat branch will be removed in v1.1.0.",
            DeprecationWarning,
            stacklevel=2,
        )
        out = []
        for cat, data in raw.items():
            applicability = data.get("applicability", "applicable")
            out.append(
                {
                    "category": cat,
                    "applicable": applicability != "not_applicable",
                    "score": int(round(data.get("score", 0))),
                    "max_score": int(round(data.get("max", data.get("max_score", 0)))),
                    "summary": data.get("summary", ""),
                    "key_findings": data.get("key_findings", []),
                }
            )
        return out
    return []


def _finding_rank(finding: dict) -> float:
    sev = SEVERITY_RANK.get(finding.get("severity", "low"), 0)
    conf = CONFIDENCE_RANK.get(finding.get("confidence", "medium"), 0.0)
    mag = float(finding.get("score_impact", {}).get("magnitude", 0)) / 10.0
    return sev * conf * mag


def _split_findings(findings: list[dict]) -> tuple[list[dict], list[dict]]:
    production: list[dict] = []
    fixture: list[dict] = []
    for f in findings:
        if is_fixture_finding(f):
            fixture.append(f)
        else:
            production.append(f)
    return production, fixture


def _resolve_use_case_profile(use_case: str | None) -> dict:
    if not use_case:
        return {}
    try:
        return load_use_case_profiles().get(use_case) or {}
    except Exception:
        return {}


def _executive_summary_md(
    scored: dict,
    blocks: list[NarrativeBlock],
    *,
    use_case: str | None,
) -> list[str]:
    scoring = scored.get("scoring") or {}
    classification = scored.get("classification") or {}
    overall = scoring.get("overall_score", "n/a")
    verdict = scoring.get("verdict", "n/a")
    archetype = classification.get("repo_archetype", "unknown")
    blockers = scored.get("hard_blockers") or []
    crit = sum(1 for b in blockers if b.get("severity") == "critical")
    high = sum(1 for b in blockers if b.get("severity") == "high")

    headline = (
        f"**Overall {overall}/100** — verdict `{verdict}` on a `{archetype}` archetype"
    )
    if crit or high:
        sev_summary: list[str] = []
        if crit:
            sev_summary.append(f"**{crit}** critical")
        if high:
            sev_summary.append(f"**{high}** high")
        headline += f", with {' and '.join(sev_summary)} blocker{'s' if (crit + high) != 1 else ''}."
    else:
        headline += ", no hard blockers."

    lines: list[str] = []
    lines.append("## Executive Summary")
    lines.append("")
    if use_case:
        lines.append(f"_Persona: **{use_case}**._")
        lines.append("")
    lines.append(headline)
    lines.append("")
    if blocks:
        lines.append(blocks[0].summary)
        lines.append("")
    # Top callouts across all blocks (de-duped, top 4 by severity).
    callouts: list[tuple[str, str]] = []
    for b in blocks:
        for c in b.callouts:
            callouts.append((c.severity, c.message))
    seen: set[str] = set()
    sorted_callouts: list[tuple[str, str]] = []
    for sev, msg in sorted(callouts, key=lambda t: -SEVERITY_RANK.get(t[0], 0)):
        if msg in seen:
            continue
        seen.add(msg)
        sorted_callouts.append((sev, msg))
        if len(sorted_callouts) >= 4:
            break
    if sorted_callouts:
        lines.append("**Key items:**")
        lines.append("")
        for sev, msg in sorted_callouts:
            lines.append(f"- `{sev}` — {msg}")
        lines.append("")
    return lines


def _scorecard_md(scored: dict, *, prod_count: int, fixture_count: int) -> list[str]:
    scoring = scored.get("scoring") or {}
    classification = scored.get("classification") or {}
    blockers = scored.get("hard_blockers") or []
    crit = sum(1 for b in blockers if b.get("severity") == "critical")
    high = sum(1 for b in blockers if b.get("severity") == "high")

    rows = [
        ("Overall", str(scoring.get("overall_score", "n/a"))),
        ("Verdict", f"`{scoring.get('verdict', 'n/a')}`"),
        ("Score confidence", str(scoring.get("score_confidence", "n/a"))),
        ("Hard blockers", f"{crit + high} ({crit} critical · {high} high)"),
        ("Production findings", str(prod_count)),
        ("Fixture-derived findings", str(fixture_count)),
        ("Archetype", str(classification.get("repo_archetype", "unknown"))),
        (
            "Classification confidence",
            f"{float(classification.get('classification_confidence') or 0.0):.2f}",
        ),
    ]
    lines = ["## Scorecard", "", "| Metric | Value |", "|---|---|"]
    for label, value in rows:
        lines.append(f"| {label} | {value} |")
    lines.append("")
    return lines


def _narrative_block_md(block: NarrativeBlock) -> list[str]:
    lines: list[str] = []
    lines.append(f"### {block.title}")
    lines.append("")
    if block.summary:
        lines.append(block.summary)
        lines.append("")
    if block.facts:
        lines.append("| Fact | Value |")
        lines.append("|---|---|")
        for fact in block.facts:
            sev_tag = f" `{fact.severity}`" if fact.severity else ""
            lines.append(f"| {fact.label}{sev_tag} | {fact.value} |")
        lines.append("")
    if block.callouts:
        for c in block.callouts:
            lines.append(f"> **`{c.severity}`** — {c.message}")
            lines.append("")
    return lines


def _hard_blockers_md(scored: dict) -> list[str]:
    blockers = scored.get("hard_blockers") or []
    lines = ["## Hard Blockers", ""]
    if not blockers:
        lines.append("_No hard blockers were triggered._")
        lines.append("")
        return lines
    lines.append(f"**{len(blockers)} blocker(s) — close before merge.**")
    lines.append("")
    for b in blockers:
        sev = (b.get("severity") or "?").upper()
        title = b.get("title", "(no title)")
        reason = b.get("reason", "")
        lines.append(f"- **`{sev}`** {title} — {reason}")
        for cr in b.get("closure_requirements") or []:
            lines.append(f"  - {cr}")
    lines.append("")
    return lines


def _category_matrix_md(category_scores: list[dict]) -> list[str]:
    lines = [
        "## Category Scoring Matrix",
        "",
        "| Category | Applicable | Score | Max | Summary |",
        "|---|---|---:|---:|---|",
    ]
    for cat in category_scores:
        applicable = "yes" if cat.get("applicable") else "no"
        if not cat.get("applicable"):
            score_cell, max_cell = "—", "—"
        else:
            score_cell = str(cat.get("score", 0))
            max_cell = str(cat.get("max_score", 0))
        summary = (cat.get("summary") or "").replace("|", "\\|")
        lines.append(
            f"| {cat.get('category', '?')} | {applicable} | "
            f"{score_cell} | {max_cell} | {summary} |"
        )
    lines.append("")
    return lines


def _findings_table_md(findings: list[dict], *, header: str) -> list[str]:
    lines = [f"### {header}", ""]
    if not findings:
        lines.append("_None._")
        lines.append("")
        return lines
    lines.append("| Severity | Category | Subcategory | Statement | Location |")
    lines.append("|---|---|---|---|---|")
    for f in sorted(findings, key=lambda x: -_finding_rank(x)):
        sev = (f.get("severity") or "info").upper()
        ev = (f.get("evidence") or [{}])[0]
        path = ev.get("path", "n/a")
        line = ev.get("line_start")
        path_ref = f"{path}:{line}" if line else path
        stmt = (f.get("statement") or "").replace("|", "\\|")
        lines.append(
            f"| `{sev}` | {f.get('category', '?')} | "
            f"`{f.get('subcategory', '?')}` | {stmt} | `{path_ref}` |"
        )
    lines.append("")
    return lines


def _findings_grouped_md(findings: list[dict]) -> list[str]:
    if not findings:
        return ["_No findings to group._", ""]
    bucket: dict[str, list[dict]] = defaultdict(list)
    for f in findings:
        bucket[f.get("category", "unknown")].append(f)
    lines: list[str] = []
    for cat in sorted(bucket.keys()):
        sorted_in_cat = sorted(
            bucket[cat], key=lambda f: SEVERITY_ORDER.get(f.get("severity", "low"), 5)
        )
        lines.append(f"#### {cat}")
        for f in sorted_in_cat:
            sev = (f.get("severity") or "info").upper()
            ev = (f.get("evidence") or [{}])[0]
            path = ev.get("path", "")
            line = ev.get("line_start")
            path_ref = f"{path}:{line}" if line else path
            lines.append(
                f"- **`{sev}`** {f.get('statement', '')} — `{path_ref}`"
            )
        lines.append("")
    return lines


def _evidence_appendix_md(findings: list[dict]) -> list[str]:
    lines = ["## Evidence Appendix", ""]
    if not findings:
        lines.append("_No findings._")
        lines.append("")
        return lines
    lines.append(f"Total findings: **{len(findings)}**")
    lines.append("")
    for f in findings[:50]:
        ev = (f.get("evidence") or [{}])[0]
        loc = ev.get("path") or "n/a"
        if ev.get("line_start"):
            loc += f":{ev['line_start']}"
        lines.append(
            f"- `{f.get('id', '?')}` `{f.get('subcategory', '?')}` — `{loc}`"
        )
    if len(findings) > 50:
        lines.append("")
        lines.append(f"_…and {len(findings) - 50} more findings (see scored.json)._")
    lines.append("")
    return lines


def render_markdown_report(scored: dict) -> str:
    """Render ``scored`` as a persona-aware Markdown report."""
    repo_meta = scored.get("repo_meta", {}) or {}
    classification = scored.get("classification", {}) or {}
    scoring = scored.get("scoring", {}) or {}
    findings = scored.get("findings") or []
    inventory = scored.get("inventory") or {}
    category_scores = _normalize_category_scores(scoring.get("category_scores", []))

    prod_findings, fixture_findings_list = _split_findings(findings)

    eff = scoring.get("effective_profile") or {}
    use_case = eff.get("use_case")
    use_case_profile = _resolve_use_case_profile(use_case)
    blocks = narrate_for_persona(scored, use_case_profile)

    lines: list[str] = []

    # Header
    lines.append(f"# SDLC Assessment Report — {repo_meta.get('name', 'unknown')}")
    lines.append("")
    lines.append(
        f"_Use case: **{use_case or 'n/a'}** · "
        f"Maturity: **{eff.get('maturity', 'n/a')}** · "
        f"Repo type: **{eff.get('repo_type', 'n/a')}**_"
    )
    lines.append("")
    lines.append(
        f"_Branch: `{repo_meta.get('default_branch', 'unknown')}` · "
        f"Analyzed at {repo_meta.get('analysis_timestamp', datetime.now(UTC).isoformat())}_"
    )
    lines.append("")

    # Executive summary (data-driven by persona)
    lines.extend(_executive_summary_md(scored, blocks, use_case=use_case))

    # Scorecard
    lines.extend(
        _scorecard_md(
            scored,
            prod_count=len(prod_findings),
            fixture_count=len(fixture_findings_list),
        )
    )

    # Persona narrative sections
    if blocks:
        lines.append(f"## Persona-aware narrative — `{use_case or 'n/a'}`")
        lines.append("")
        lines.append("_Sections below are generated from the use-case profile's `narrative_emphasis` terms. Each block is grounded in the scored payload — no LLM, no invented prose._")
        lines.append("")
        for b in blocks:
            lines.extend(_narrative_block_md(b))

    # Hard blockers
    lines.extend(_hard_blockers_md(scored))

    # Quantitative inventory
    lines.append("## Quantitative Inventory")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("|---|---|")
    for key, label in INVENTORY_FIELDS:
        value = inventory.get(key)
        lines.append(f"| {label} | {value if value is not None else 'n/a'} |")
    lines.append(f"| Network exposure | {classification.get('network_exposure', 'n/a')} |")
    lines.append(f"| Release surface | {classification.get('release_surface', 'n/a')} |")
    lines.append("")

    # Category scoring matrix
    lines.extend(_category_matrix_md(category_scores))

    # Detailed findings
    lines.append("## Detailed Findings")
    lines.append("")
    lines.extend(_findings_table_md(prod_findings, header="Production findings"))
    lines.append("### Production findings by category")
    lines.append("")
    lines.extend(_findings_grouped_md(prod_findings))
    if fixture_findings_list:
        lines.append("### Fixture / non-production findings")
        lines.append("")
        lines.append(
            f"_{len(fixture_findings_list)} finding(s) come from `tests/fixtures/`, "
            "`examples/`, `vendor/` or similar non-production paths. They are real "
            "signals (the tool is detecting its own intentional fixtures) but should "
            "not be confused with findings in production source._"
        )
        lines.append("")
        lines.extend(
            _findings_table_md(fixture_findings_list, header="Fixture findings (segregated)")
        )

    # Evidence appendix
    lines.extend(_evidence_appendix_md(findings))

    return "\n".join(lines) + "\n"


__all__ = ["render_markdown_report"]
